from __future__ import annotations

from dataclasses import dataclass

from .contracts import (
    DegradationLevel,
    GeneratedPackage,
    GenerationRequest,
    ProviderKind,
    stable_id,
)


@dataclass(frozen=True)
class TemplateStyle:
    hook: str = "{current} just changed — and the reason matters."
    setup: str = "According to {source}, {metric} is now {current}{previous_clause}."
    cause: str = "The clearest verified explanation is {cause}."
    comparison: str = "For context, {comparison}."
    ending: str = "The next number to watch is {next_metric}."
    generic_ending: str = "The important part is what this number changes next."


class DeterministicWriter:
    """Evidence-bound script writer that requires no language model."""

    def __init__(self, style: TemplateStyle | None = None) -> None:
        self.style = style or TemplateStyle()

    def write(self, request: GenerationRequest, *, created_at: str = "") -> GeneratedPackage:
        if not request.facts:
            raise ValueError("template fallback requires at least one evidence fact")
        failures = [failure for fact in request.facts for failure in fact.validate()]
        if failures:
            raise ValueError("invalid evidence: " + ",".join(sorted(set(failures))))
        primary = request.facts[0]
        paragraphs = [
            self.style.hook.format(current=primary.current_value),
            self.style.setup.format(
                source=primary.source_name,
                metric=primary.metric,
                current=primary.current_value,
                previous_clause=f", compared with {primary.previous_value}" if primary.previous_value else "",
            ),
        ]
        if primary.verified_cause:
            paragraphs.append(self.style.cause.format(cause=primary.verified_cause))
        if primary.comparison:
            paragraphs.append(self.style.comparison.format(comparison=primary.comparison))
        paragraphs.append(
            self.style.ending.format(next_metric=primary.next_metric)
            if primary.next_metric
            else self.style.generic_ending
        )
        for extra in request.facts[1:3]:
            paragraphs.insert(-1, f"Another verified point: {extra.metric} is {extra.current_value}, according to {extra.source_name}.")
        script = " ".join(paragraphs)
        title = f"{primary.metric}: {primary.current_value}"
        description = (
            f"Source-based explainer generated by the local deterministic fallback. "
            f"Primary source: {primary.source_name}."
        )
        payload = {"request_id": request.request_id, "script": script, "provider": "template"}
        return GeneratedPackage(
            package_id=stable_id("pkg", payload),
            channel=request.channel,
            topic=request.topic,
            provider=ProviderKind.TEMPLATE,
            degradation=DegradationLevel.DEGRADED,
            script=script,
            title=title,
            description=description,
            source_urls=tuple(dict.fromkeys(fact.source_url for fact in request.facts)),
            qa_passed=False,
            approved=False,
            evergreen=request.evergreen,
            created_at=created_at,
            metadata={
                "request_id": request.request_id,
                "template_version": "1",
                "claims_bound_to_evidence": True,
                "requires_human_or_existing_QA_approval": True,
            },
        )
