"""THE LAST TEXT BACKEND: a mailbox ChatGPT answers between runs.

`shared.script_generator._call_llm` walks Groq -> Gemini -> Anthropic ->
the Claude CLI. On 2026-09-21 all four were gone at once (404, 429, unset,
"You've hit your session limit"), and every question the pipeline asks a
brain — does this segment support the headline, write this story's words,
invent this beat's depiction — came back UNAVAILABLE. The editorial gate,
correctly fail-closed, then held 83 stories pre-render.

This backend cannot answer NOW: the ChatGPT subscription has no API. It
answers NEXT RUN. A question is hashed; if an answer with that hash has
been committed, it is returned as if a model had just said it. If not, the
question is appended to today's ask file and the caller gets the same
"unavailable" it would have got anyway — but the next run finds the
answer where the previous one left the question. For the editorial gate,
which asks the SAME question about the same story every run, that turns
"held forever while the brains are out" into "held one run".

Layout:

    exchange/asks/<YYYYMMDD>.json          the day's questions, keyed by hash
    exchange/asks/<YYYYMMDD>.answers.json  ChatGPT's answers, same keys

Non-negotiable: an answer is a STRING the caller parses exactly as it
would parse a model's reply — the thesis judge still accepts only an exact
`true`, the package validator still validates. Nothing here is trusted;
it is only available.
"""
from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ASKS_DIR = REPO / "exchange" / "asks"
SCHEMA = "shorts-ask-batch/v1"
MAX_CHARS = 64_000


class AnswerPending(RuntimeError):
    """The question is filed; the answer has not been committed yet."""


def ask_key(system: str, user: str) -> str:
    return hashlib.sha256((system + "\n\x00\n" + user).encode("utf-8")).hexdigest()[:16]


def _today() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d")


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def find_answer(key: str, asks_dir: Path | None = None) -> str | None:
    """Any committed answer for this key, newest day first."""
    asks_dir = Path(asks_dir or ASKS_DIR)
    if not asks_dir.exists():
        return None
    for ap in sorted(asks_dir.glob("*.answers.json"), reverse=True):
        try:
            answers = json.loads(ap.read_text())
        except Exception:  # noqa: BLE001
            continue
        if not isinstance(answers, dict):
            continue
        row = (answers.get("answers") or {}).get(key)
        if isinstance(row, dict) and isinstance(row.get("answer"), str):
            return row["answer"]
        if isinstance(row, str):
            return row
    return None


def file_ask(system: str, user: str, *, caller: str = "",
             asks_dir: Path | None = None) -> str:
    """Append the question to today's batch (idempotent by key). Returns
    the key. Never raises into the caller's fallback chain."""
    key = ask_key(system, user)
    try:
        asks_dir = Path(asks_dir or ASKS_DIR)
        asks_dir.mkdir(parents=True, exist_ok=True)
        bp = asks_dir / f"{_today()}.json"
        batch = {"schema": SCHEMA, "date": _today(), "asks": {},
                 "answer_path": f"exchange/asks/{_today()}.answers.json",
                 "how_to_answer": (
                     "For every key under `asks`, answer the `user` message "
                     "under the `system` instruction EXACTLY as the model "
                     "they were written for would — same format, JSON where "
                     "JSON is asked for, no commentary. Write answer_path as "
                     '{"schema": "shorts-ask-answers/v1", "answers": {<key>: '
                     '{"answer": "<your reply>", "by": "chatgpt", "at": '
                     '"<ISO-8601 UTC>"}}} and commit it. Do not edit this file.')}
        if bp.exists():
            try:
                old = json.loads(bp.read_text())
                if isinstance(old, dict) and isinstance(old.get("asks"), dict):
                    batch["asks"] = old["asks"]
            except Exception:  # noqa: BLE001
                pass
        if key not in batch["asks"]:
            if len(system) + len(user) > MAX_CHARS:
                user = user[:MAX_CHARS - len(system) - 40] + "\n[truncated]"
            batch["asks"][key] = {"filed": _now(), "caller": caller,
                                  "system": system, "user": user}
            bp.write_text(json.dumps(batch, indent=1, ensure_ascii=False) + "\n")
            print(f"[mailbox] ask filed: {key} ({caller or 'llm'})", flush=True)
            write_index(asks_dir)
    except Exception as e:  # noqa: BLE001
        print(f"[mailbox] could not file ask: {type(e).__name__}: {e}", flush=True)
    return key


def write_index(asks_dir: Path | None = None) -> Path | None:
    """`exchange/asks/OPEN.json` — every batch with unanswered keys."""
    asks_dir = Path(asks_dir or ASKS_DIR)
    try:
        open_batches = []
        for bp in sorted(asks_dir.glob("????????.json")):
            try:
                batch = json.loads(bp.read_text())
            except Exception:  # noqa: BLE001
                continue
            keys = list((batch.get("asks") or {}).keys())
            pending = [k for k in keys if find_answer(k, asks_dir) is None]
            if pending:
                open_batches.append({"batch": f"exchange/asks/{bp.name}",
                                     "answer_path": batch.get("answer_path"),
                                     "pending": len(pending), "keys": pending})
        idx = {"schema": "shorts-ask-index/v1", "updated": _now(), "open": open_batches,
               "how": "Open each `batch` (raw), answer every listed key, commit "
                      "`answer_path` (merge into it if it exists)."}
        asks_dir.mkdir(parents=True, exist_ok=True)
        ip = asks_dir / "OPEN.json"
        ip.write_text(json.dumps(idx, indent=1, ensure_ascii=False) + "\n")
        return ip
    except Exception as e:  # noqa: BLE001
        print(f"[mailbox] ask index not written: {e}", flush=True)
        return None


def enabled() -> bool:
    """On by default in CI (where a later run exists to read the answer);
    `LLM_MAILBOX=0` switches it off. Off outside CI unless `LLM_MAILBOX=1`,
    so a laptop test run does not litter the exchange with asks."""
    v = os.environ.get("LLM_MAILBOX")
    if v is not None:
        return v not in ("0", "", "off", "false")
    return bool(os.environ.get("GITHUB_ACTIONS"))


def call(system: str, user: str, *, caller: str = "") -> str:
    """The backend: a committed answer, or file the ask and say so."""
    key = ask_key(system, user)
    got = find_answer(key)
    if got is not None:
        print(f"[mailbox] answered from the mailbox: {key}", flush=True)
        return got
    if not enabled():
        raise AnswerPending("mailbox disabled outside CI (LLM_MAILBOX=1 to force)")
    file_ask(system, user, caller=caller)
    raise AnswerPending(f"answer pending in exchange/asks ({key})")
