#!/usr/bin/env python3
"""Prove the /shared refactor produces BYTE-IDENTICAL render output to the
pre-refactor make_short.py.

How it works
------------
The only stages whose code moved into shared/ that affect output BYTES are:
gameplay pick+trim, audio mix, ASS authoring, and the final compose. This
harness drives those stages through BOTH code paths on identical, pinned
inputs and byte-compares the resulting MP4:

  * "before" = the pre-refactor make_short.py at a pinned git ref (BASELINE_REF,
               overridable with --baseline-ref), fetched fresh and imported as
               a throwaway module.
  * "after"  = the new shared/ core.

Determinism controls:
  * synthetic source + gameplay generated by ffmpeg (no network).
  * TTS and Whisper are NOT exercised — they need network/models and do not
    affect render math. We substitute a fixed synthetic voice clip and a fixed
    word list, identical for both paths.
  * random is re-seeded with the same value before each path so pick_gameplay's
    trim point matches.

This is a render-math equivalence proof. It does not (and cannot, offline)
exercise edge-tts or whisper themselves — those modules were moved verbatim
and are unchanged.

Exit 0 if the two MP4s are byte-identical, else 1.
"""
from __future__ import annotations

import hashlib
import importlib.util
import random
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# The last commit where make_short.py was self-contained (before the shared/
# extraction). The proof renders through THIS exact file and through the
# current shared/ core. Override with --baseline-ref <git-ref> if needed.
BASELINE_REF = "509d4a9"

SEED = 1234
SRC_DUR = 6.0
GAMEPLAY_DUR = 20.0
DURATION_CAP = 22.0

FIXED_WORDS_TEXT = [
    "this", "is", "a", "fixed", "caption", "track", "used", "to",
    "stand", "in", "for", "whisper", "output", "deterministically",
]


def sh(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True, capture_output=True, text=True)


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def make_synthetic_source(out: Path) -> None:
    sh([
        "ffmpeg", "-y", "-loglevel", "error",
        "-f", "lavfi", "-i", f"testsrc2=size=640x360:rate=25:duration={SRC_DUR}",
        "-f", "lavfi", "-i", f"sine=frequency=440:duration={SRC_DUR}",
        "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-shortest", str(out),
    ])


def make_synthetic_gameplay(out: Path) -> None:
    sh([
        "ffmpeg", "-y", "-loglevel", "error",
        "-f", "lavfi", "-i", f"testsrc=size=1280x720:rate=25:duration={GAMEPLAY_DUR}",
        "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p",
        "-an", str(out),
    ])


def make_synthetic_voice(out: Path) -> None:
    sh([
        "ffmpeg", "-y", "-loglevel", "error",
        "-f", "lavfi", "-i", f"sine=frequency=220:duration={SRC_DUR}",
        "-c:a", "libmp3lame", "-q:a", "4", str(out),
    ])


def import_old_make_short(tmp: Path, baseline_ref: str = BASELINE_REF):
    """Fetch the pre-refactor make_short.py from a pinned git ref and import it
    as a throwaway module with its gameplay dir pointed at our synthetic clip."""
    old_src = subprocess.run(
        ["git", "show", f"{baseline_ref}:make_short.py"],
        cwd=ROOT, check=True, capture_output=True, text=True,
    ).stdout
    old_path = tmp / "make_short_old.py"
    old_path.write_text(old_src)
    spec = importlib.util.spec_from_file_location("make_short_old", old_path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod  # dataclass introspection needs this registered
    spec.loader.exec_module(mod)
    return mod


def render_old(mod, source: Path, gameplay_dir: Path, voice: Path, out: Path, wd: Path) -> None:
    mod.GAMEPLAY_DIR = gameplay_dir  # redirect the module-global the old code reads
    target = min(mod.ffprobe_duration(source), DURATION_CAP)
    random.seed(SEED)
    gameplay = mod.pick_gameplay("random", target, wd)
    audio = mod.mix_audio(source, voice, wd)
    words = [mod.Word(i * 0.4, i * 0.4 + 0.4, t) for i, t in enumerate(FIXED_WORDS_TEXT)]
    chunks = mod.group_words(words, per_chunk=3)
    subs = wd / "captions.ass"
    mod.write_ass(chunks, subs)
    mod.compose(source, gameplay, audio, subs, out, target)


def render_new(source: Path, gameplay_dir: Path, voice: Path, out: Path, wd: Path) -> None:
    import shared
    target = min(shared.ffprobe_duration(source), DURATION_CAP)
    random.seed(SEED)
    gameplay = shared.pick_gameplay("random", target, wd, gameplay_dir)
    audio = shared.mix_audio(source, voice, wd)
    words = [shared.Word(i * 0.4, i * 0.4 + 0.4, t) for i, t in enumerate(FIXED_WORDS_TEXT)]
    chunks = shared.group_words(words, per_chunk=3)
    subs = wd / "captions.ass"
    shared.write_ass(chunks, subs)
    shared.compose(source, gameplay, audio, subs, out, target)


def main() -> int:
    import argparse
    ap = argparse.ArgumentParser(description="Prove shared/ render is byte-identical to pre-refactor make_short.py.")
    ap.add_argument("--baseline-ref", default=BASELINE_REF,
                    help=f"git ref of the pre-refactor make_short.py (default {BASELINE_REF})")
    args = ap.parse_args()

    tmp = Path(tempfile.mkdtemp(prefix="verify_"))
    print(f"workdir: {tmp}  baseline-ref: {args.baseline_ref}")

    source = tmp / "source.mp4"
    voice = tmp / "voice.mp3"
    gp_dir = tmp / "gameplay"
    gp_dir.mkdir()
    make_synthetic_source(source)
    make_synthetic_gameplay(gp_dir / "random_synth.mp4")
    make_synthetic_voice(voice)
    print("synthetic inputs built (source + gameplay + voice)")

    # ASS-content equivalence (separate from the render, a direct check)
    import shared
    old = import_old_make_short(tmp, args.baseline_ref)
    words_old = [old.Word(0, 0.4, "alpha"), old.Word(0.4, 0.8, "beta"), old.Word(0.8, 1.2, "gamma")]
    words_new = [shared.Word(0, 0.4, "alpha"), shared.Word(0.4, 0.8, "beta"), shared.Word(0.8, 1.2, "gamma")]
    p_old = tmp / "old.ass"
    p_new = tmp / "new.ass"
    old.write_ass(old.group_words(words_old, 3), p_old)
    shared.write_ass(shared.group_words(words_new, 3), p_new)
    ass_match = p_old.read_bytes() == p_new.read_bytes()
    print(f"write_ass byte-identical: {ass_match}")

    wd_old = tmp / "wd_old"; wd_old.mkdir()
    wd_new = tmp / "wd_new"; wd_new.mkdir()
    out_old = tmp / "out_old.mp4"
    out_new = tmp / "out_new.mp4"

    print(f"rendering BEFORE (make_short.py @ {args.baseline_ref}) ...")
    render_old(old, source, gp_dir, voice, out_old, wd_old)
    print("rendering AFTER (shared/) ...")
    render_new(source, gp_dir, voice, out_new, wd_new)

    h_old = sha256(out_old)
    h_new = sha256(out_new)
    size_old = out_old.stat().st_size
    size_new = out_new.stat().st_size
    identical = out_old.read_bytes() == out_new.read_bytes()

    print()
    print(f"  before: {size_old:>9} bytes  sha256={h_old}")
    print(f"  after : {size_new:>9} bytes  sha256={h_new}")
    print()
    if identical and ass_match:
        print("RESULT: BYTE-IDENTICAL ✅  (render output and ASS both match)")
        return 0
    print("RESULT: MISMATCH ❌")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
