from __future__ import annotations

from .models import AdoptionPhase, Component, EvidenceClaim, MasterHandoff, Risk


SAFE_TEST_PREFIXES = (
    "python -m unittest",
    "python -m review_prototypes.",
    "python -m compileall",
)

SACRED_GUARDS = (
    "Publishing remains frozen until an explicitly authorized production phase.",
    "The sovereign showrunner BLOCK can never be converted into SHIP by prototype, bridge, repair, or handoff code.",
    "Do not change WEIGHTS, AUTOFAIL_CHECKS, MIN_SCORE, decide_verdict, or fail-closed publish behavior as part of adoption.",
    "Posted logs, OAuth tokens, expected-channel guards, workflow permissions, upload idempotency, and production state are sacred.",
    "Every adoption phase is a separate commit with an acceptance gate and an immediate rollback path.",
    "Baseline and shadow comparisons must use the same slug, evidence, source data, narration, and metric definitions.",
    "Unknown or missing evidence is never silently converted to zero, neutral, or approval.",
    "Channel identity and doctrine remain channel-owned and cannot be overwritten by shared utilities or learned patterns.",
)

COMPONENTS = (
    Component(
        "core_attempts",
        "Transactional attempts and quality contracts",
        "review_prototypes/attempt_store.py",
        "Immutable attempts, quality contracts, keep-best promotion, and rollback primitives.",
        "reviewed_reference",
        "none",
        ("python -m unittest review_prototypes.test_attempt_store",),
        adoption_lane="safety_foundation",
    ),
    Component(
        "implementation_runtime",
        "Reference implementation runtime",
        "review_prototypes/implementation",
        "Isolated adapters, manifests, repository semantics, and deterministic runtime contracts.",
        "reviewed_reference",
        "none",
        (
            "python -m unittest review_prototypes.implementation.test_adapters",
            "python -m unittest review_prototypes.implementation.test_runtime",
        ),
        ("core_attempts",),
        "safety_foundation",
    ),
    Component(
        "quality_orchestration",
        "Semantic planning and quality state",
        "review_prototypes/next_level",
        "Semantic scene plans, judge ensembles, benchmark phases, pattern catalog, and fail-closed quality state.",
        "reviewed_reference",
        "none",
        (
            "python -m unittest review_prototypes.next_level.test_semantic_scene_planner",
            "python -m unittest review_prototypes.next_level.test_judge_ensemble",
            "python -m unittest review_prototypes.next_level.test_quality_state_machine",
            "python -m unittest review_prototypes.next_level.test_quality_orchestrator_blueprint",
        ),
        ("implementation_runtime",),
        "safety_foundation",
    ),
    Component(
        "content_system",
        "Source-backed content system",
        "review_prototypes/content_system",
        "Source registry, premise scoring, claim-bound story compilation, and queue diversity.",
        "tested_isolated",
        "none",
        ("python -m unittest review_prototypes.content_system.test_content_system",),
        ("quality_orchestration",),
        "content_quality",
    ),
    Component(
        "analytics_learning",
        "Channel analytics and experiments",
        "review_prototypes/channel_analytics",
        "Strict observations, guarded experiment decisions, pattern summaries, and one-active-experiment storage.",
        "tested_isolated",
        "none",
        ("python -m unittest review_prototypes.channel_analytics.test_analytics_system",),
        ("content_system",),
        "learning",
    ),
    Component(
        "retention_system",
        "Retention and ending system",
        "review_prototypes/retention_system",
        "Hook structures, pacing limits, tension checks, repetition detection, and payoff selection.",
        "tested_isolated",
        "none",
        ("python -m unittest review_prototypes.retention_system.test_retention_system",),
        ("content_system",),
        "viewer_quality",
    ),
    Component(
        "channel_operations",
        "Release portfolio and readiness",
        "review_prototypes/channel_operations",
        "Fail-closed readiness, diverse batch selection, one-experiment enforcement, and scheduling.",
        "tested_isolated",
        "none",
        ("python -m unittest review_prototypes.channel_operations.test_channel_operations",),
        ("analytics_learning",),
        "operations",
    ),
    Component(
        "visible_render_lab",
        "Viewer-facing render lab",
        "review_prototypes/visible_quality/render_lab",
        "Deterministic 9:16 effects, choreography, captions, camera, sound cues, callbacks, and visual variants.",
        "tested_isolated",
        "none",
        (
            "python -m unittest review_prototypes.visible_quality.render_lab.test_render_lab",
            "python -m unittest review_prototypes.visible_quality.render_lab.test_variant_lab",
        ),
        ("retention_system",),
        "viewer_quality",
    ),
    Component(
        "perceptual_polish",
        "Perceptual polish lab",
        "review_prototypes/visible_quality/polish_lab",
        "Adaptive typography, collision-free captions, sound planning, transition continuity, and archetype-specific rendering.",
        "tested_isolated",
        "none",
        ("python -m unittest review_prototypes.visible_quality.polish_lab.test_polish_lab",),
        ("visible_render_lab",),
        "viewer_quality",
    ),
    Component(
        "global_continuity",
        "Global continuity lab",
        "review_prototypes/visible_quality/continuity_lab",
        "Whole-video motion flow, frame-snapped audio, occupancy, rhythm, and transition optimization.",
        "tested_isolated",
        "none",
        ("python -m unittest review_prototypes.visible_quality.continuity_lab.test_continuity_lab",),
        ("perceptual_polish",),
        "viewer_quality",
    ),
    Component(
        "sandbox_execution",
        "Sandbox adapters",
        "review_prototypes/sandbox_adapters",
        "Path-contained renderer and judge execution with allowlisted commands and forced publishing freeze.",
        "tested_isolated",
        "none",
        ("python -m unittest review_prototypes.sandbox_adapters.test_sandbox_adapters",),
        ("implementation_runtime",),
        "safety_foundation",
    ),
    Component(
        "full_video_proof",
        "Complete-video proof",
        "review_prototypes/full_video_proof",
        "Immutable run evidence, locked versions, consecutive-run gates, and tamper detection.",
        "tested_isolated",
        "none",
        ("python -m unittest review_prototypes.full_video_proof.test_full_video_proof",),
        ("sandbox_execution",),
        "verification",
    ),
    Component(
        "observability",
        "Audit and incident observability",
        "review_prototypes/observability",
        "Hash-chained events, incidents, dead-letter records, and reproducible summaries.",
        "tested_isolated",
        "none",
        ("python -m unittest review_prototypes.observability.test_observability",),
        ("sandbox_execution",),
        "verification",
    ),
    Component(
        "release_safety",
        "Release quarantine and restoration",
        "review_prototypes/release_safety",
        "Immutable manifests, quarantine, canonical promotion, tamper refusal, and verified restoration.",
        "tested_isolated",
        "none",
        ("python -m unittest review_prototypes.release_safety.test_release_safety",),
        ("full_video_proof", "observability"),
        "verification",
    ),
    Component(
        "completion_lab",
        "Isolated closure lab",
        "review_prototypes/completion_lab",
        "End-to-end deterministic pipeline, fault injection, audit, proof, release, golden fixtures, and closure gates.",
        "tested_isolated_complete",
        "none",
        ("python -m unittest discover -s review_prototypes/completion_lab -t . -p 'test_*.py'",),
        ("release_safety",),
        "verification",
    ),
    Component(
        "integration_bridge",
        "Production-shaped shadow integration bridge",
        "review_prototypes/integration_bridge",
        "Duck-typed Story adaptation, non-mutating application, contract probe, manifest bridge, verdict routing, and patch blueprints.",
        "tested_isolated_complete",
        "shadow_only",
        ("python -m unittest -v review_prototypes.integration_bridge.test_integration_bridge",),
        ("global_continuity", "completion_lab"),
        "production_migration",
    ),
    Component(
        "launch_closure",
        "Launch rehearsal and Claude execution path",
        "review_prototypes/launch_closure",
        "Matched baseline/shadow MP4 rehearsal, two-pass review, restoration drills, launch gates, and ordered production patch targets.",
        "tested_isolated_complete",
        "preview_only",
        (
            "python -m unittest -v review_prototypes.launch_closure.test_launch_closure",
            "python -m review_prototypes.launch_closure.cli --out /tmp/shorts-launch-rehearsal",
        ),
        ("integration_bridge",),
        "production_migration",
    ),
    Component(
        "capability_studio",
        "Capability Studio and free toolchain",
        "review_prototypes/capability_studio",
        "Review-only providers, research, media, audio, video, QA, replay, scene routing, and free-toolchain adoption references.",
        "reference_requires_execution",
        "none",
        (
            "python -m unittest review_prototypes.capability_studio.test_capability_studio",
            "python -m unittest review_prototypes.capability_studio.test_free_capabilities",
            "python -m unittest review_prototypes.capability_studio.test_toolchain_adoption",
        ),
        ("sandbox_execution",),
        "capability_expansion",
        "Run every suite and doctor command before porting a provider or executor.",
    ),
    Component(
        "subscription_fallback",
        "Subscription-independent posting fallback",
        "review_prototypes/subscription_fallback",
        "Approved queue, provider health, deterministic writing, degradation policy, buffering, upload idempotency, and fallback orchestration.",
        "reference_requires_execution",
        "none",
        ("python -m unittest review_prototypes.subscription_fallback.test_subscription_fallback",),
        ("channel_operations", "release_safety"),
        "operational_independence",
        "Adopt only after proving same-day AI generation is not required for safe posting.",
    ),
    Component(
        "professional_media_os",
        "Professional Media OS",
        "review_prototypes/professional_media_os",
        "Immutable knowledge, evidence, lineage, candidate laboratory, patterns, governance, portfolio, and operator intelligence.",
        "uncalibrated_reference",
        "reference_only",
        (
            "python -m unittest review_prototypes.professional_media_os.test_professional_media_os review_prototypes.professional_media_os.test_lineage review_prototypes.professional_media_os.test_patterns_version",
            "python -m review_prototypes.professional_media_os.cli demo",
        ),
        ("analytics_learning", "launch_closure"),
        "institutional_learning",
        "Adopt record schemas and lineage first; ranking authority comes much later.",
    ),
    Component(
        "scorecards",
        "System scorecards",
        "review_prototypes/system_scorecard",
        "Evidence-weighted snapshots that keep production wiring and real-world proof separate from isolated completion.",
        "tested_isolated",
        "none",
        (
            "python -m unittest review_prototypes.system_scorecard.test_scorecard",
            "python -m unittest review_prototypes.system_scorecard.test_completion_snapshot",
            "python -m unittest review_prototypes.system_scorecard.test_sprint3_snapshot",
        ),
        ("completion_lab",),
        "verification",
    ),
)

PHASES = (
    AdoptionPhase(
        "phase_00_orientation",
        "Read-only orientation",
        "Understand scope, branch state, safety constraints, and evidence before changing anything.",
        (
            "cat review_prototypes/claude_master_handoff/PLAYBOOK.md",
            "python -m review_prototypes.claude_master_handoff.cli summary",
            "python -m review_prototypes.claude_master_handoff.cli validate --repo .",
        ),
        (
            "master handoff validates",
            "PR remains draft and publishing remains frozen",
            "Claude can name the selected adoption lane and its authority ceiling",
        ),
        ("none; read-only",),
        (
            "any referenced path is missing",
            "the branch or production contract has drifted",
            "the selected goal is not explicit",
        ),
        authority_ceiling="none",
    ),
    AdoptionPhase(
        "phase_01_preflight",
        "Critical isolated preflight",
        "Run the contract bridge, launch closure, and the selected lane's isolated tests.",
        (
            "python -m unittest -v review_prototypes.integration_bridge.test_integration_bridge",
            "python -m unittest -v review_prototypes.launch_closure.test_launch_closure",
            "python -m review_prototypes.launch_closure.cli --out /tmp/shorts-launch-rehearsal",
        ),
        (
            "all frozen contracts pass",
            "14/14 launch gates pass",
            "temporary rehearsal leaves production and publishing untouched",
        ),
        ("delete temporary rehearsal output; no repository change",),
        (
            "any suite fails",
            "contract probe reports drift",
            "publishing becomes enabled",
        ),
        ("phase_00_orientation",),
        authority_ceiling="none",
    ),
    AdoptionPhase(
        "phase_02_record_contracts",
        "Record-only contracts",
        "Add stable IDs, optional metadata, evidence references, and lineage records without changing selection or rendering.",
        ("implement one reviewed contract slice on a separate Claude branch",),
        (
            "same input produces byte-equivalent production artifact",
            "older manifests still load",
            "unknowns remain explicit",
            "no production decision changes",
        ),
        ("revert the phase commit",),
        (
            "production artifact hash changes",
            "channel identity moves into shared code",
            "new state touches posted logs, secrets, or production analytics",
        ),
        ("phase_01_preflight",),
        authority_ceiling="record_only",
    ),
    AdoptionPhase(
        "phase_03_shadow_bridge",
        "Shadow creative bridge",
        "Apply compiled kind, performance, caption, transition, and audio metadata to deep copies and emit separate shadow evidence.",
        ("apply launch manifest patch targets 1-3 behind an explicit preview flag",),
        (
            "baseline and shadow use identical slug, sources, data, and narration",
            "default production behavior is unchanged when flag is off",
            "shadow metadata cannot override source truth or showrunner verdicts",
        ),
        ("disable preview flag and revert the phase commit",),
        (
            "fallback/novelty guarantees regress",
            "source truth changes",
            "a blocked candidate becomes eligible",
        ),
        ("phase_02_record_contracts",),
        (
            "data_learning/story.py",
            "data_learning/viz_director.py",
            "data_learning/charts.py",
        ),
        "shadow_only",
    ),
    AdoptionPhase(
        "phase_04_preview_renderer",
        "Preview-only renderer consumption",
        "Let the real renderer consume verified shadow metadata only in explicit preview mode.",
        ("apply launch manifest patch target 4 and render a matched baseline/shadow pair",),
        (
            "both complete MP4s exist",
            "publishing is frozen",
            "shadow wins objective quality checks",
            "default render remains identical with preview flag off",
        ),
        ("unset preview flag and revert renderer commit",),
        (
            "baseline/shadow inputs differ",
            "temporary MP4 is incomplete or corrupt",
            "production default changes",
        ),
        ("phase_03_shadow_bridge",),
        ("data_learning/studio_render.py",),
        "preview_only",
    ),
    AdoptionPhase(
        "phase_05_sovereign_review",
        "Complete-video sovereign review",
        "Add diagnostics only, then require two consecutive SHIP verdicts with no auto-fails.",
        ("apply launch manifest patch target 5 and review the full shadow MP4 twice",),
        (
            "WEIGHTS, AUTOFAIL_CHECKS, MIN_SCORE, decide_verdict, and fail-closed behavior are unchanged",
            "two consecutive complete-video verdicts agree and SHIP",
            "no auto-fail is present",
        ),
        ("drop diagnostic metadata and retain the baseline",),
        (
            "reviewer verdicts disagree",
            "reviewer returns no score",
            "any auto-fail is present",
            "showrunner authority is weakened",
        ),
        ("phase_04_preview_renderer",),
        ("scripts/showrunner_review.py",),
        "preview_only",
    ),
    AdoptionPhase(
        "phase_06_bounded_repair",
        "Bounded keep-best repair",
        "Feed bridge-generated structural candidates through the existing blind, monotone repair path.",
        ("apply launch manifest patch targets 6-7",),
        (
            "incumbent is retained unless challenger wins under the existing rule",
            "repair budget remains bounded",
            "worse cuts never replace better cuts",
        ),
        ("revert repair commits and use the current VARIANTS table",),
        (
            "repair becomes an unbounded reroll",
            "challenger replaces incumbent without winning",
            "bridge evidence can change BLOCK to SHIP",
        ),
        ("phase_05_sovereign_review",),
        ("scripts/scene_repair.py", "scripts/repair_loop.py"),
        "preview_only",
    ),
    AdoptionPhase(
        "phase_07_private_holdout",
        "Frozen/private holdout",
        "Exercise the integrated preview path without public release and verify restoration.",
        ("run a bounded private/frozen holdout with explicit kill switch",),
        (
            "restoration returns exact prior canonical behavior",
            "no channel guardrail regresses",
            "no upload or posted-log mutation occurs",
        ),
        ("disable integration flag and restore the prior canonical plan",),
        (
            "rollback hash differs",
            "upload path is touched",
            "guardrail regression appears",
        ),
        ("phase_06_bounded_repair",),
        authority_ceiling="bounded_canary",
    ),
    AdoptionPhase(
        "phase_08_independence",
        "Operational independence",
        "Adopt fallback queue and selected free capabilities without coupling publishing to live AI availability.",
        (
            "run capability_studio and subscription_fallback isolated suites",
            "adopt one provider or fallback slice at a time behind a kill switch",
        ),
        (
            "approved queue remains source of truth",
            "upload idempotency is preserved",
            "provider failure degrades safely instead of stopping or duplicating posts",
        ),
        ("disable the selected provider/fallback flag and return to prior queue behavior",),
        (
            "same-day generation becomes required for posting",
            "duplicate upload risk appears",
            "unapproved content becomes eligible",
        ),
        ("phase_07_private_holdout",),
        authority_ceiling="bounded_canary",
    ),
    AdoptionPhase(
        "phase_09_media_os_records",
        "Professional Media OS record layer",
        "Adopt stable records, shadow capture, lineage, and institutional history before ranking authority.",
        (
            "run all Professional Media OS isolated tests and demo",
            "port identifiers and immutable record contracts only",
            "add physically separate record-only shadow outputs",
        ),
        (
            "production artifacts and uploads are byte-equivalent with shadow on/off",
            "events are append-only and traceable",
            "no ranking or publishing authority exists",
        ),
        ("disable the shadow writer and revert the record-contract commit",),
        (
            "prototype single-writer ledger is copied blindly into concurrent production",
            "unknown evidence is coerced to zero",
            "record layer influences candidate selection",
        ),
        ("phase_02_record_contracts",),
        authority_ceiling="record_only",
    ),
    AdoptionPhase(
        "phase_10_media_os_shadow_lab",
        "Professional Media OS shadow laboratory",
        "Build a representative historical corpus and calibrate candidate evaluators without production authority.",
        ("follow docs/future/CLAUDE_PROFESSIONAL_MEDIA_OS_ADOPTION.md phases E-F",),
        (
            "representative benchmark corpus exists",
            "false rejection and false approval are measured separately",
            "production selection is unchanged",
        ),
        ("disable shadow lab outputs; retain historical records",),
        (
            "unusual winners are systematically rejected",
            "candidate utility is presented as causal or calibrated without evidence",
            "channel doctrine is overwritten",
        ),
        ("phase_09_media_os_records",),
        authority_ceiling="shadow_only",
    ),
)

RISKS = (
    Risk(
        "risk_scope_sprawl",
        "Claude attempts to integrate everything at once",
        "More than one adoption lane or more than one authority jump is proposed in a single phase.",
        ("Select one explicit goal and one phase.", "Use separate commits and acceptance gates."),
        ("Revert the phase and return to phase_00_orientation.",),
        "critical",
    ),
    Risk(
        "risk_showrunner_weakening",
        "Quality gate is altered to make more videos pass",
        "Changes touch score weights, auto-fails, threshold, verdict logic, or publish fail direction.",
        ("Permit diagnostics only.", "Compare immutable symbol hashes before and after."),
        ("Revert immediately and retain the blocked artifact."),
        "critical",
    ),
    Risk(
        "risk_publish_escape",
        "Preview work reaches upload or posted state",
        "Publishing flag, uploader, token routing, workflow permission, or posted log is touched.",
        ("Keep publishing frozen.", "Use temporary/private paths and a kill switch."),
        ("Stop execution, disable the feature flag, and reconcile state before any rerun."),
        "critical",
    ),
    Risk(
        "risk_contract_drift",
        "Production symbols or files change before adoption",
        "Frozen SHA/symbol probe differs from the handoff snapshot.",
        ("Rerun the probe and remap the live contract.", "Update the blueprint before coding."),
        ("Do not apply the old patch; return to read-only orientation."),
        "high",
    ),
    Risk(
        "risk_false_confidence",
        "Synthetic or heuristic evidence is presented as audience proof",
        "A reference score, counterfactual, or synthetic fixture is used as a performance claim.",
        ("Label evidence status explicitly.", "Require mature real-channel outcomes for audience claims."),
        ("Remove the claim and return the system to shadow/reference authority."),
        "high",
    ),
    Risk(
        "risk_metric_mixing",
        "Incompatible metric definitions are compared",
        "Different definitions, windows, or maturity states are treated as one series.",
        ("Persist metric definition versions and eligibility.", "Refuse incompatible samples."),
        ("Discard the comparison and recompute with eligible baselines."),
        "high",
    ),
    Risk(
        "risk_duplicate_upload",
        "Fallback or replay starts a second upload",
        "An existing upload reservation is not reconciled before another upload begins.",
        ("Resume/poll existing upload first.", "Preserve upload idempotency and posted-log authority."),
        ("Stop new upload attempts and reconcile the existing reservation."),
        "critical",
    ),
    Risk(
        "risk_pattern_overreach",
        "Learned pattern overrides channel identity or exclusions",
        "A generic pattern applies despite channel doctrine, exclusions, or deprecation.",
        ("Channel identity remains sovereign.", "Exclusions and deprecated versions override positive matches."),
        ("Disable the pattern version and append a reversal decision."),
        "high",
    ),
)

EVIDENCE = (
    EvidenceClaim(
        "launch_closure_tests",
        "verified",
        "54/54",
        "review_prototypes/launch_closure/fixtures/test_results.txt",
        "Recorded launch-closure suite.",
    ),
    EvidenceClaim(
        "launch_gates",
        "verified",
        "14/14",
        "review_prototypes/launch_closure/fixtures/sprint10_summary.json",
    ),
    EvidenceClaim(
        "integration_bridge_tests",
        "verified",
        "39/39",
        "review_prototypes/integration_bridge/fixtures/sprint9_summary.json",
    ),
    EvidenceClaim(
        "continuity_tests",
        "verified",
        "29/29",
        "review_prototypes/visible_quality/continuity_lab/fixtures/sprint8_summary.json",
    ),
    EvidenceClaim(
        "polish_tests",
        "verified",
        "30/30",
        "review_prototypes/visible_quality/polish_lab/fixtures/sprint7_summary.json",
    ),
    EvidenceClaim(
        "render_lab_tests",
        "verified",
        "31/31",
        "review_prototypes/visible_quality/render_lab/fixtures/quality_summary.json",
    ),
    EvidenceClaim(
        "isolated_closure_tests",
        "verified",
        "25/25",
        "review_prototypes/completion_lab/fixtures/test_summary.json",
    ),
    EvidenceClaim(
        "professional_media_os_tests",
        "declared_unverified",
        "25 declared",
        "review_prototypes/professional_media_os/ADOPTION_MANIFEST.json",
        "Connector environment did not execute these tests; Claude must run them.",
    ),
    EvidenceClaim(
        "production_wiring",
        "not_claimed",
        "0%",
        "review_prototypes/launch_closure/fixtures/sprint10_scorecard.json",
    ),
    EvidenceClaim(
        "real_channel_performance",
        "not_claimed",
        "0%",
        "review_prototypes/launch_closure/fixtures/sprint10_scorecard.json",
    ),
)

FIRST_SESSION_COMMANDS = (
    "git status --short --branch",
    "cat review_prototypes/claude_master_handoff/PLAYBOOK.md",
    "python -m review_prototypes.claude_master_handoff.cli summary",
    "python -m review_prototypes.claude_master_handoff.cli validate --repo .",
    "python -m unittest -v review_prototypes.integration_bridge.test_integration_bridge",
    "python -m unittest -v review_prototypes.launch_closure.test_launch_closure",
    "python -m review_prototypes.launch_closure.cli --out /tmp/shorts-launch-rehearsal",
)

DECISION_ROUTES = {
    "improve_current_video_quality": "phase_01_preflight -> phase_03_shadow_bridge -> phase_04_preview_renderer -> phase_05_sovereign_review",
    "make_posting_independent_of_live_ai": "phase_01_preflight -> phase_08_independence",
    "add_free_media_or_tool_capability": "phase_01_preflight -> phase_08_independence using capability_studio",
    "build_institutional_learning": "phase_02_record_contracts -> phase_09_media_os_records -> phase_10_media_os_shadow_lab",
    "improve_sources_and_story_premises": "content_system only; remain review-only until a separate contract mapping is approved",
    "inspect_or_repair_quality_failures": "full_video_proof + observability + release_safety + bounded repair path",
}


def build_master_handoff() -> MasterHandoff:
    handoff = MasterHandoff(
        schema_version="claude-master-handoff/v1",
        branch="agent/claude-roadmap-review",
        pull_request=174,
        status="review_only_unwired",
        components=COMPONENTS,
        phases=PHASES,
        risks=RISKS,
        evidence=EVIDENCE,
        sacred_guards=SACRED_GUARDS,
        first_session_commands=FIRST_SESSION_COMMANDS,
        decision_routes=DECISION_ROUTES,
    )
    handoff.validate()
    return handoff
